# -*- coding: utf-8 -*-
"""Zomato Data Analysis

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/19FFjvXar0WAYFqHYrhwVgs-14lFUqjQj

# **Zomato Data Analysis by Python**
Project By Ayush Kumar
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns



dataframe = pd.read_csv("/content/Zomato data .csv")

dataframe.iloc[10:101, 0:4]



"""Create the dataframe"""

dataframe = pd.read_csv("Zomato data .csv")

print(dataframe)

dataframe



"""convert the data type of column-rate"""

def handleRate(value):
    value = str(value).split('/')
    value = value[0];
    return float(value)

dataframe['rate']=dataframe['rate'].apply(handleRate)
print(dataframe)

"""

```
# This is formatted as code
```

"""

dataframe.head()

dataframe.info()



"""Type of Resturant"""

dataframe.head()

sns.countplot(x=dataframe['listed_in(type)'])
plt.xlabel("type of resturant")



"""Conclusion: Majority of the resturant falls in dinning Category."""

dataframe.head()

grouped_data = dataframe.groupby('listed_in(type)')['votes'].sum()
result = pd.DataFrame({'votes': grouped_data})
plt.plot(result, c="green", marker="o")
plt.xlabel("Type of restaurant", c="red", size=20)
plt.ylabel("votes", c="red", size=20)



"""Conclusion: Dinning restaurants has recieved maximum votes."""

dataframe.head()

plt.hist(dataframe['rate'],bins = 5)
plt.title("ratings distribution")



"""Conclusion: The majority restaurant recieved ratings from 3.6 to 6."""

dataframe.head()



"""Average Order Spending by couples"""

dataframe.head()

couple_data=dataframe['approx_cost(for two people)']
sns.countplot(x=couple_data)



"""Conclusion: The majority of couples prefer restaurants with an approximate cost of 300 rupees."""



"""Which mode recieves maximim rating"""

dataframe.head()

plt.figure(figsize = (6,6))
sns.boxplot(x='online_order', y = 'rate', data = dataframe)



"""Conclusion: Offline order recieved lower rating in comparision to online order."""

dataframe.head()

pivot_table = dataframe.pivot_table(index='listed_in(type)', columns='online_order', aggfunc='size', fill_value=0)
sns.heatmap(pivot_table, annot=True, cmap="YlGnBu", fmt='d')
plt.title("Heatmap")
plt.xlabel("Online Order")
plt.ylabel("Listed In (Type)")
plt.show()

"""Conclusion: Dining restaurants primarily accept offline orders, whereas cafes primarily receive online orders. This suggests that clients prefer to place orders in person at restaurants, but prefer online ordering at cafes."""

